# app/config/security.yml
jms_security_extra:
    secure_all_services: false
    expressions: true
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    providers:
        in_memory: # nom du provider
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
    firewalls:
        dev:  #nom du parefeu
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false #pas d authentification ni de identification
        main:
            pattern:   ^/
            anonymous: true #authenfication en anonimous ok
            provider:  in_memory
            form_login: 
                login_path: login # nom de la route de la page de login
                check_path: login_check # nom de la route qui vérifie l utilisateur , pas besoin de controller pour elle symfony gere tout seul. il faudra juste mettre le chemin (path de la route)
            logout:
                path:   logout # nom de la route logout (symfony gere le controller aussi)
                target: /blog  #URL vers laquelle sera redirigé le visiteur après sa déconnexion.
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }